name: Fetch Top 1000
on: 
  schedule:
    - cron: '23 12 * * 5'
jobs:
  Fetch-Top-1000-Stars:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Process Stars
        run: python process_stars.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push